### ISSUE TITLE
Player "account" not created if player has played before

### ISSUE THREAD

**Issue by TobyMinceraft** [ShaneBeeStudios/BeeConomy#1]
Literally as the title suggests, if a player has played before a BeeConomy account is not created, but new players do.
This would normally be fine as I could use Skript to manually create one, but I cannot do so either as myself or the console because the code requires the player to have an account before the value can be modified. If I can find a way to do so using `skript-reflect` I will, but I don't have enough experience with it for it to become useful.

**Comment by ShaneBeee** [comment]
Ah thanks for letting me know. 
I did very little testing with this plug-in but I’ll look into it soon.

**Comment by TobyMinceraft** [comment]
Works like a charm! Found another fun bug though. I'll make a new issue, as it only indirectly pertains to this.
