### ISSUE TITLE
Issue with getting player's balance in Skript

### ISSUE THREAD

**Issue by TobyMinceraft** [ShaneBeeStudios/BeeConomy#2]
As I'm sure you know, Skript allows users to get a player's balance so long as Vault and a compatible economy plugin are installed.
Now that my previous issue has been resolved, players' balances are properly set at login, but it doesn't show up properly when using Skript. I've tried a couple of methods to do this, but I have yet to get it to work.

Things I have tried:
`broadcast player's balance`
- Using `!` effect command, doesn't broadcast anything, no errors in console
- Using custom Skript command, shows `An internal error occurred while attempting to perform this command` and an [error](https://pastebin.com/8rKkXRpB) in the console

`broadcast placeholder "vault_eco_balance" from player`
- Using `!` effect command, doesn't broadcast anything, no errors in console
- Using custom Skript command, doesn't show anything (when sent as a `"string"`, broadcasts `<none>`), no errors in console

Plugins (24): BeeConomy*, BetterPortals, ChestSort, ConsoleSpamFix, CraftingStore, DiSky, EditableSign, LuckPerms, PlaceholderAPI, ProtocolLib, RuntimeSkriptAddonPatcher, SkBee, Skellett, SkImage*, SkQuery, Skript, skript-placeholders, skript-reflect, skript-yaml, skUtilities*, TreeFeller, Vault, ViaBackwards, ViaVersion

Skript Version: 2.6
Server Software:  Paper

**Comment by ShaneBeee** [comment]
I see the mistake I made, clearly I didnt test something when I made a change in my code, WHOOPS!
I'll get that fixed soon

**Comment by ShaneBeee** [comment]
Ok, bug has been fixed, you can get/test the build from here:
https://github.com/ShaneBeeStudios/BeeConomy/actions/runs/1710781545

Just click on "BeeConomy - Artifact" at the bottom, unzip it and you'll have the jar there
I did a quick test, and it seemed to work, but double check your issues and let me know how it goes.
I'll close this issue once I actually do a release

**Comment by ShaneBeee** [comment]
Fixed in latest release 1.0.1
